import Navbar from "../component/common/NavBar";
import "./../globals.css";
import { Inter } from "next/font/google";

// Optional: use a font like Inter
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  
       <>
       <Navbar/>
        {children}
       </>
    
  );
}
